# Generated by Django 4.2.7 on 2024-03-02 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BroadcastNotification",
        ),
    ]
